/**
 *  This file is used for visualization
 *  Author: jianzhuozhu
 *  Date: 2021-7-27
 */

#pragma once
#include "putnDataType.h"

namespace putn
{
namespace visualization
{
/**
 * @brief visualize the grid map
 */
void visualizeWorld(const std::shared_ptr<World>& world, ros::Publisher* world_vis_pub);

/**
 * @brief visualize the plane of the nodes along the path generated by PF-RRT*
 */
void visualizePlane(const std::vector<Node*>& solution, ros::Publisher* surf_vis_pub);

/**
 * @brief visualize the start point and the end point of PF-RRT*
 */
void visualizeOriginAndGoal(const std::vector<Node*>& pts, ros::Publisher* origin_and_goal_vis_pub);

/**
 * @brief visualize the path generated by PF-RRT*
 */
void visualizePath(const std::vector<Node*>& solution, ros::Publisher* path_vis_pub);

/**
 * @brief visualize the tree of PF-RRT*
 */
void visualizeTree(const std::vector<Node*>& tree, ros::Publisher* tree_vis_pub);
}   // namespace visualization

}   // namespace putn